Loaded dependency [python3/3.10.12]: gcc/11.4.0-binutils-2.40
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0

Switching from python3/3.8.2 to python3/3.10.12
  Loading requirement: gcc/11.4.0-binutils-2.40 sqlite3/3.42.0
2024-02-11 11:27:11.133646: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-11 11:27:11.133686: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-11 11:27:11.133716: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-11 11:27:32.247264: W external/xla/xla/service/gpu/runtime/support.cc:58] Intercepted XLA runtime error:
INTERNAL: jaxlib/gpu/blas_kernels.cc:100: operation gpuStreamSynchronize(stream) failed: an illegal memory access was encountered
2024-02-11 11:27:32.247670: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2593] Execution of replica 0 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: jaxlib/gpu/blas_kernels.cc:100: operation gpuStreamSynchronize(stream) failed: an illegal memory access was encountered; current tracing scope: custom-call.4; current profiling annotation: XlaModule:#hlo_module=jit__lambda_,program_id=131#.
2024-02-11 11:27:32.261523: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: jaxlib/gpu/blas_kernels.cc:100: operation gpuStreamSynchronize(stream) failed: an illegal memory access was encountered; current tracing scope: custom-call.4; current profiling annotation: XlaModule:#hlo_module=jit__lambda_,program_id=131#.
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)

  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 643, in wrapper
    return func(*args, **kwargs)

  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/generators.py", line 67, in __call__
    (ts,xss,chartss,*_) = self.product((jnp.repeat(self.x0s[0],self.x_samples,axis=0),

jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: jaxlib/gpu/blas_kernels.cc:100: operation gpuStreamSynchronize(stream) failed: an illegal memory access was encountered; current tracing scope: custom-call.4; current profiling annotation: XlaModule:#hlo_module=jit__lambda_,program_id=131#.


Traceback (most recent call last):
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/train_score.py", line 545, in <module>
    train_score()
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/train_score.py", line 523, in train_score
    train_s1(M=M,
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/trainxt.py", line 131, in train_s1
    initial_params = model.init(jrandom.PRNGKey(seed), next(train_dataset)[:,:(2*N_dim+1)])
  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_utils.py", line 82, in _eager_dataset_iterator
    for elem in ds:
  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 809, in __next__
    return self._next_internal()
  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 772, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3028, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 5888, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.UnknownError: {{function_node __wrapped__IteratorGetNext_output_types_1_device_/job:localhost/replica:0/task:0/device:CPU:0}} XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: jaxlib/gpu/blas_kernels.cc:100: operation gpuStreamSynchronize(stream) failed: an illegal memory access was encountered; current tracing scope: custom-call.4; current profiling annotation: XlaModule:#hlo_module=jit__lambda_,program_id=131#.
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)

  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 643, in wrapper
    return func(*args, **kwargs)

  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/generators.py", line 67, in __call__
    (ts,xss,chartss,*_) = self.product((jnp.repeat(self.x0s[0],self.x_samples,axis=0),

jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: jaxlib/gpu/blas_kernels.cc:100: operation gpuStreamSynchronize(stream) failed: an illegal memory access was encountered; current tracing scope: custom-call.4; current profiling annotation: XlaModule:#hlo_module=jit__lambda_,program_id=131#.


	 [[{{node PyFunc}}]] [Op:IteratorGetNext] name: 
2024-02-11 11:27:32.731992: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x785ac40; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.733209: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x7fc1dcc73b60; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.735470: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x6bf9ab0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.737280: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x92aebb0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.741163: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x770b550; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.741940: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x792fa00; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.742355: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x6c37dc0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.742745: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x7ad4500; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.743091: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x77aa0c0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.743477: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x7c07da0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.745221: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0xa53ba20; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.745999: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0xa027240; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.746396: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x91f1910; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.748345: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x9e04fc0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.749745: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0xa7b1bc0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.751232: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x7fc1dce364d0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.754332: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x7fc1dd8147f0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.756185: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x7fc1dcca1a60; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:32.758024: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x7fc1ddf8aff0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:33.012714: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:763] failed to free device memory at 0x7fc1ab747a00; result: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2024-02-11 11:27:33.013771: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:674] failed to unload module 0x7fc1dd56f5c0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
