Loaded dependency [python3/3.10.12]: gcc/11.4.0-binutils-2.40
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0

Switching from python3/3.8.2 to python3/3.10.12
  Loading requirement: gcc/11.4.0-binutils-2.40 sqlite3/3.42.0
2024-04-28 09:06:47.884929: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-28 09:06:47.884969: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-28 09:06:47.884998: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/train_score.py", line 296, in <module>
    train_score()
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/train_score.py", line 274, in train_score
    train_s1(M=M,
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/trainxt.py", line 113, in train_s1
    new_state, loss_val = update(state, data)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/trainxt.py", line 61, in update
    loss, gradients = value_and_grad(loss_fun)(state.params, state.state_val, rng_key, data)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/trainxt.py", line 55, in loss_fun
    return loss_model(generator, s1_model, x0, xt, t, dW, dt)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/loss_fun.py", line 33, in vsm_s1fun
    divs = vmap(lambda x0, xt, chart, t: generator.M.div((xt, chart), 
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/loss_fun.py", line 33, in <lambda>
    divs = vmap(lambda x0, xt, chart, t: generator.M.div((xt, chart), 
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/manifolds/riemannian/metric.py", line 98, in <lambda>
    M.div = lambda x,X: jnp.trace(jacfwdx(X)(x))+.5*jnp.dot(X(x),gradx(M.logAbsDet)(x))
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/autodiff/tuple.py", line 41, in jacf
    return jacfwd(fxchart,argnums=0)(x[0],x[1],*args,**kwargs)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/autodiff/tuple.py", line 39, in fxchart
    return f((x,chart),*args,**kwargs)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/loss_fun.py", line 34, in <lambda>
    lambda x: generator.grad_local(s1_model, x0, x, t)))(x0,xts,chartts,t)
TypeError: TMSampling.grad_local() takes 3 positional arguments but 5 were given
terminate called without an active exception
/zhome/77/8/118225/.lsbatch/1714255233.21640177.shell: line 38: 19227 Aborted                 python3 train_score.py --manifold Sphere --dim 10 --s1_loss_type vsm --s2_loss_type dsmvr --load_model 0 --T_sample 0 --t 0.01 --train_net s1 --max_T 1.0 --lr_rate 0.0002 --epochs 50000 --x_samples 64 --t_samples 256 --repeats 16 --samples_per_batch 32 --dt_steps 1000 --save_step 100 --seed 2712
