Loaded dependency [python3/3.10.12]: gcc/11.4.0-binutils-2.40
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0

Switching from python3/3.8.2 to python3/3.10.12
  Loading requirement: gcc/11.4.0-binutils-2.40 sqlite3/3.42.0
2024-01-30 04:08:34.007475: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-30 04:08:34.007512: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-30 04:08:34.015158: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
/zhome/77/8/118225/.local/lib/python3.10/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/zhome/77/8/118225/.local/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/train_score.py", line 507, in <module>
    train_score()
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/train_score.py", line 462, in train_score
    train_s2(M=M,
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/trainxt.py", line 300, in train_s2
    state, loss_val = update(state, data)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/trainxt.py", line 263, in update
    loss, gradients = value_and_grad(loss_fun)(state.params, state.state_val, rng_key, data)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/trainxt.py", line 253, in loss_fun
    loss = jnp.mean(vmap(
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/trainxt.py", line 229, in f
    s2 = generator.proj_hess(s1_model, s2_model, x0, xt, t)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/statistics/score_matching/generators.py", line 276, in proj_hess
    Fx = self.M.F(x)
  File "/zhome/77/8/118225/Desktop/Projects/score_diffusion_mean/score_diffusion_mean/jaxgeometry/manifolds/Cylinder.py", line 40, in <lambda>
    jnp.stack([x[0][1]+x[1][1],self.radius*jnp.cos(self.theta+x[1][0]+x[0][0]),self.radius*jnp.sin(self.theta+x[1][0]+x[0][0])]))
  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 728, in op
    return getattr(self.aval, f"_{name}")(self, *args)
  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 341, in _getitem
    return lax_numpy._rewriting_take(self, item)
  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4323, in _rewriting_take
    return _gather(arr, treedef, static_idx, dynamic_idx, indices_are_sorted,
  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4332, in _gather
    indexer = _index_to_gather(shape(arr), idx)  # shared with _scatter_update
  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4433, in _index_to_gather
    idx = _canonicalize_tuple_index(len(x_shape), idx)
  File "/zhome/77/8/118225/.local/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4766, in _canonicalize_tuple_index
    raise IndexError(
IndexError: Too many indices for array: 1 non-None/Ellipsis indices for dim 0.
2024-01-30 04:09:12.409872: W tensorflow/core/kernels/data/generator_dataset_op.cc:108] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
